server:
  port: 4040
spring:
  profiles:
    active: db ,jwt ,mail
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username_}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${host}
    port: ${port}
    username: ${mail-name}
    password: ${mail-pw}
    properties:
      mail:
        smtp:
          auth: ${auth}
          starttls:
            enable: ${enable}